# Conda environment
#
# Install:
# mamba env create -f environment.yml
# conda activate dl3irfs

name: dl3irfs
channels:
  - conda-forge
  - defaults
dependencies:
  - pre-commit
  - pip
  - pip:
      - ogadf-schema
