# Conda environment
#
# Install:
# mamba env create -f environment.yml
# conda activate EDconvert
#
name: EDconvert

channels:
  - astropy
  - conda-forge

dependencies:
  - numpy
  - astropy
  - click
  - python
  - uproot
